name: biohackers
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  lottie: ^3.3.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.0
  firebase_storage: ^11.0.0
  intl: ^0.18.1
  share_plus: ^10.0.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hayvan_hucresi.png
    - assets/bitki_hucresi.png
    - assets/logo.png
    - assets/dna_animation.json


flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  web: true
  fullscreen: true
